@extends('admin.admin_index') 

@section('order_management') 





<div class="main-panel">
                
    <div class="content-wrapper">
        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Categories Table</h4>
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>
                                            Id
                                        </th>
                                        <th>
                                            Name
                                        </th>
                                        <th>
                                            Adress
                                        </th>
                                        <th>
                                            Product Name
                                        </th>
                                        <th>
                                            Quantity
                                        </th>
                                        <th>
                                            Color
                                        </th>
                                        <th>
                                            Placed at
                                        </th>
                                        <th>
                                            Status
                                        </th>

                                        <th>
                                            Update
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                                                    
                                                                                                                                                                                                                                    <tr>
                                    <td>1</td>
                                        
                                                                                                                                    <td>John Doe</td>
                                                <td>131, Dhanmondi, Dhaka, 1229 ,Bangladesh</td>
                                                
                                                
                                    
                                        <td>
                                        
                                            HP Probook X360 440 G1
                                        
                                        </td>
                                    <td>
                                            1
                                        </td>
                                        <td>
                                            <div style="height:25px;width:25px;margin:5px;display:inline-block;background-color: #000000"></div>
                                        </td>
                                        
                                        <td>
                                            2019-02-02 07:32:33
                                        </td>
                                        <td>
                                        On Process
                                        </td>
                                        <td>
                                            <form method="post" style="display:inline-block">
                                                <input type="hidden" name="_token" value="F4ps472TR07olNPVwBDooUcvcsjwvKBpAGVPioIQ">
                                                <input type="hidden" value="1" name="orderId">
                                                <select name="stat">
                                                                                                                                                    <option value="Placed">Placed</option>

                                                    
                                                                                                    
                                                                                                                                                    <option value="Delivered">Delivered</option>

                                                    
                                                                                                                                                    <option value="Cancel">Cancel</option>

                                                    
                                                                                                </select>
                                                <input type="submit" class="btn btn-sm btn-warning" value="Update">
                                            </form>
                                        </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                            <tr>
                                    <td>2</td>
                                        
                                                                                                                                                                                                                        <td>Shakib Mostahid</td>
                                                <td>Mirpur 10, Dhaka, 1772 ,Bangladesh</td>
                                                
                                                
                                    
                                        <td>
                                        
                                            Google Pixel 3 (64 GB)
                                        
                                        </td>
                                    <td>
                                            1
                                        </td>
                                        <td>
                                            <div style="height:25px;width:25px;margin:5px;display:inline-block;background-color: #c0c0c0"></div>
                                        </td>
                                        
                                        <td>
                                            2019-02-11 14:12:27
                                        </td>
                                        <td>
                                        Cancel
                                        </td>
                                        <td>
                                            <form method="post" style="display:inline-block">
                                                <input type="hidden" name="_token" value="F4ps472TR07olNPVwBDooUcvcsjwvKBpAGVPioIQ">
                                                <input type="hidden" value="2" name="orderId">
                                                <select name="stat">
                                                                                                                                                    <option value="Placed">Placed</option>

                                                    
                                                                                                                                                    <option value="On Process">On Process</option>

                                                    
                                                                                                                                                    <option value="Delivered">Delivered</option>

                                                    
                                                                                                    
                                                                                                </select>
                                                <input type="submit" class="btn btn-sm btn-warning" value="Update">
                                            </form>
                                        </td>
                                                                                                                                                                                                                                                                                
                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                            <tr>
                                    <td>6</td>
                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <td>Ayomi Hridy</td>
                                                <td>Uttora, Dhaka, 1233 ,Bangladesh</td>
                                                
                                                
                                    
                                        <td>
                                        
                                            Google Pixel 3 (64 GB)
                                        
                                        </td>
                                    <td>
                                            1
                                        </td>
                                        <td>
                                            <div style="height:25px;width:25px;margin:5px;display:inline-block;background-color: #c0c0c0"></div>
                                        </td>
                                        
                                        <td>
                                            2019-02-11 17:07:40
                                        </td>
                                        <td>
                                        Delivered
                                        </td>
                                        <td>
                                            <form method="post" style="display:inline-block">
                                                <input type="hidden" name="_token" value="F4ps472TR07olNPVwBDooUcvcsjwvKBpAGVPioIQ">
                                                <input type="hidden" value="6" name="orderId">
                                                <select name="stat">
                                                                                                                                                    <option value="Placed">Placed</option>

                                                    
                                                                                                                                                    <option value="On Process">On Process</option>

                                                    
                                                                                                    
                                                                                                                                                    <option value="Cancel">Cancel</option>

                                                    
                                                                                                </select>
                                                <input type="submit" class="btn btn-sm btn-warning" value="Update">
                                            </form>
                                        </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <tr>
                                    <td>11</td>
                                        
                                                                                                                                                                                                                        <td>Shakib Mostahid</td>
                                                <td>Mirpur 10, Dhaka, 1772 ,Bangladesh</td>
                                                
                                                
                                    
                                        <td>
                                        
                                            JBL Xtreme 2 Portable
                                        
                                        </td>
                                    <td>
                                            1
                                        </td>
                                        <td>
                                            <div style="height:25px;width:25px;margin:5px;display:inline-block;background-color: #400080"></div>
                                        </td>
                                        
                                        <td>
                                            2019-02-11 17:09:49
                                        </td>
                                        <td>
                                        Cancel
                                        </td>
                                        <td>
                                            <form method="post" style="display:inline-block">
                                                <input type="hidden" name="_token" value="F4ps472TR07olNPVwBDooUcvcsjwvKBpAGVPioIQ">
                                                <input type="hidden" value="11" name="orderId">
                                                <select name="stat">
                                                                                                                                                    <option value="Placed">Placed</option>

                                                    
                                                                                                                                                    <option value="On Process">On Process</option>

                                                    
                                                                                                                                                    <option value="Delivered">Delivered</option>

                                                    
                                                                                                    
                                                                                                </select>
                                                <input type="submit" class="btn btn-sm btn-warning" value="Update">
                                            </form>
                                        </td>
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection